from . import blacklist_customer
from . import res_partner_inherit
from . import res_conifg_settings
from . import mis_device_installation_inherit
from . import mis_invoice_inherit
from . import mis_renewal_inherit
from . import mis_sale_inherit
from . import mis_ticket_inherit
from . import mis_warranty_inherit
